# -*- coding: utf-8 -*-
"""Bank_marketing_data_cleansing_using_Spark.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1f0f4VZACs_ypLU-OeEqpWrZxrwhSBNQg
"""

!wget https://raw.githubusercontent.com/futurexskill/bigdata/master/bank_prospects.csv

!ls

!wget https://dlcdn.apache.org/spark/spark-3.3.1/spark-3.3.1-bin-hadoop3.tgz

!ls

!tar -xvf spark-3.3.1-bin-hadoop3.tgz

!ls

!ls spark-3.3.1-bin-hadoop3

!ls /usr/lib/jvm

import os

os.environ["JAVA_HOME"] = "/usr/lib/jvm/java-11-openjdk-amd64"
os.environ["SPARK_HOME"] = "/content/spark-3.3.1-bin-hadoop3"

!ls /content/spark-3.3.1-bin-hadoop3

!pip install findspark

import findspark

findspark.init()

from pyspark.sql import SparkSession

spark = SparkSession.builder.master("local[*]").getOrCreate()

!wget https://raw.githubusercontent.com/futurexskill/bigdata/master/bank_prospects.csv

!ls

bankProspectsDF = spark.read.csv("bank_prospects.csv",header=True)

bankProspectsDF.show()

bankProspectsDF1 = bankProspectsDF.filter(bankProspectsDF['country']!='unknown')

bankProspectsDF1.show()

bankProspectsDF1.printSchema()

from pyspark.sql.types import IntegerType,FloatType

bankProspectsDF2 = bankProspectsDF1.withColumn("age",bankProspectsDF1["age"].cast(IntegerType())).withColumn("salary",bankProspectsDF1["salary"].cast(FloatType()))

"""Changing the datatype of column"""

bankProspectsDF2.printSchema()

from pyspark.sql.functions import mean

mean_age_val = bankProspectsDF2.select(mean(bankProspectsDF2['age'])).collect()

type(mean_age_val)

mean_age_val

mean_age = mean_age_val[0][0]

mean_age

mean_salary_val = bankProspectsDF2.select(mean(bankProspectsDF2['salary'])).collect()

mean_salary = mean_salary_val[0][0]

mean_salary

bankProspectsDF2.show()

bankProspectsDF3 = bankProspectsDF2.na.fill(mean_age,["age"])

bankProspectsDF3.show()

bankProspectsDF4 = bankProspectsDF3.na.fill(mean_salary,['salary'])

bankProspectsDF4.show()

bankProspectsDF4.printSchema()

bankProspectsDF4.write.format("csv").save("bank_prospects_transformed")

!ls

!ls bank_prospects_transformed

!cat part-00000-0efc1f1f-336b-4025-abe6-e081feab4799-c000.csv

!cat bank_prospects_transformed/bank_part-00000-0efc1f1f-336b-4025-abe6-e081feab4799-c000.csv

!cat bank_prospects_transformed/part-00000-0efc1f1f-336b-4025-abe6-e081feab4799-c000.csv

